### PR TITLE
fix PrivacyInfo.xcprivacy should be placed in SVProcessHUD.bundle #1125

### PR DESCRIPTION
**Pull request by leekkk2**
fix   PrivacyInfo.xcprivacy should be placed in SVProcessHUD.bundle #1125

### CODE REVIEW

**Comment by ondev** [comment]
@honkmaster @juliensaad Please merge this PR.

**Comment by juliensaad** [comment]
Thank you, merged

**Comment by x0000ff** [comment]
@leekkk2 and juliensaad, thanks a lot for fixing and merging this Pull Request 🙇🏼 
So, could we expect a release soon?

**Comment by mitsuke2020** [comment]
@leekkk2 @juliensaad 
Thanks for fixing PrivacyInfo file. 
But this change seems cause a build error.

I use Cocopoads like the below Podfile code which targets this commit.

`pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD', :commit => 'a8160a193787467e55ae8ea0effac8ad2b479d85'`

Build error like below. 

`Multiple commands produce '/Users/dev/Library/Developer/Xcode/DerivedData/Project-txdcaeqbdvewehqjhtyqanmdewax/Build/Products/Debug-iphoneos/SVProgressHUD/SVProgressHUD.framework/SVProgressHUD.bundle'`

It seems conflict with the existed images resources folder `SVProgressHUD.bundle`.

~~One quick solution is that modify the images resources folder `SVProgressHUD.bundle`  to the other name (Exp. `SVProgressHUD-resources.bundle`). And in `SVProgressHUD.m` the URLForResource of imageBundle also need modify to this new name.~~

One solution is that, in the SVProgressHUD.podspec file, modify the PrivacyInfo.xcprivacy‘s resource_bundles name to other name. If possible, please consider merge PR #1136.
And could we expect a release as soon as possible?

**Pull request merged**
