### PR TITLE
Added some Unit test

### PR DESCRIPTION
**Pull request by matteogobbi**
- added target for tests;
- integrated pods project;
- integrated Kiwi for TDD;
- wrote some tests.

### CODE REVIEW

**Comment by istx25** [comment]
:+1:

**Comment by honkmaster** [comment]
I am not a fan of including an additional framework for doing unit tests. This is especially true because our intention is to keep the 'SVProgressHud' as simple as possible and let it work out of the box.

**Comment by matteogobbi** [comment]
Hi, I don't get your point. The pod will remain the same as now without including any file. The project will instead integrate a test target that is extremely useful as you probably knows.

This library has been part of the chosen pods for the international event Test Jam that was yesterday and today here in London, San Francisco and New York, and the idea was to add unit tests. 

Anyway, your library, your choice. 

Cheers.

**Comment by honkmaster** [comment]
@samvermette What do you think?

**Comment by honkmaster** [comment]
Will close for now as we do not plan to integrate the test target.

**Pull request closed without merging**
