### PR TITLE
Fix SVProgressHUD calling UIKit API from background thread

### PR DESCRIPTION
**Pull request by PowerPan**
Fix Dispatch main Error
This should fix Issue #814

### CODE REVIEW

**Comment by honkmaster** [comment]
Please choose "better" titles. This makes the overview and merging a lot simpler.

**Comment by PowerPan** [comment]
@honkmaster You are right ;) Sry  now it should be better

**Comment by PowerPan** [comment]
@honkmaster for the moment please don't accept this pull request
this need some more work and testing

**Comment by PowerPan** [comment]
Now it is working fine for me un my application

**Comment by datwelk** [comment]
I don't think this change is the right approach - one should simply not call any `SVProgressHUD` method from a background thread, since `SVProgressHUD` is a UI element. Instead of wrapping the singleton access method in a main thread dispatch call, code calling `SVProgressHUD` should be wrapped in such a dispatch call.

**Comment by mickeyl** [comment]
I agree with @datwelk, `UIKit` is largely main thread only, hence is `SVProgressHUD`. This means the burden to get this right in a multithreaded scenario is on the actually caller, not the library itself. Thus, please don't merge this.

**Comment by juliensaad** [comment]
@datwelk @mickeyl Thanks for your input. I agree with this and think we can close as this shouldn't be merged.

**Comment by deepumukundan** [comment]
@datwelk @mickeyl Properly designed API's should prevent mis-use and/or prevent issues happening in the first place. Agreed that code calling SVProgressHUD should call it on the main thread for its API to work correctly, but being a UI level framework, I believe SVProgressHUD should also try to correct the users from doing so (maybe log an exception if not called in main thread) instead of silently failing. Apple's UIKit api's don't log anything, but doesn't mean that opensource frameworks need to follow suite.

I would take exception logging or correction to move the call to main thread automatically anyday over silently failing. @honkmaster @PowerPan

**Comment by juliensaad** [comment]
@deepumukundan I agree with many of your points. Yes, a framework should as much as possible try to guide users in the right direction. 

In this specific case though I think the Main Thread Checker, which is now active by default in Xcode 9, should be enough to handle this potential issue.

https://developer.apple.com/documentation/code_diagnostics/main_thread_checker

**Pull request closed without merging**
