### PR TITLE
Add SPM support

### PR DESCRIPTION
**Pull request by sereivoanyong**

### CODE REVIEW

**Comment by kristiyandobrev** [comment]
I see potential warnings with XCode 12 since there is `iOS 8` mentioned in the SPM package. I suggest adding Swift 5.3 specific SPM package and [checking this article for reference](https://josephduffy.co.uk/posts/supporting-multiple-swift-package-versions-without-breaking-compatibility)

**Comment by AndrewBennet** [comment]
Other than the above mentioned warnings, this fork seems to work great. Would be good to have this merged in!

**Comment by ethanwa** [comment]
Can we get this merged in now if possible? Thanks!

**Comment by mavinion** [comment]
I would also love to see this merged

**Comment by kcates94** [comment]
I would also love to see this merged.

**Comment by sveinhal** [comment]
Please merge 🙌

**Comment by kristiyandobrev** [comment]
Any update on merging this ? :)

**Comment by manuelneves** [comment]
merge would be appreciated

**Comment by mrgrauel** [comment]
Please add SPM support

**Comment by sereivoanyong** [comment]
Make sure to point to latest commit as it contains a fix for invalid header layout on Xcode 12.5

**Comment by rromanchuk** [comment]
@sereivoanyong want to just take over with your fork? i can help. Even just to add some minimal maintenance to this project to at least give people time to move off.

**Comment by mohdabdurraafay** [comment]
What's stopping this PR to be merged? It's been open for a year now.

**Review by nazgu1 — APPROVED** [review]

**Comment by iowais-dev** [comment]
please help me how to add this to my project using SPM!

**Comment by OuSS-90** [comment]
I need also to use it for my project using SPM, please merge it

**Comment by godLoveY** [comment]
您好，邮件已收到

**Comment by AlexandreHauber** [comment]
Does someone else get this trying to use https://github.com/sereivoanyong/SVProgressHUD as the package?

Screenshot 2023-01-29 at 14 17 52

**Comment by godLoveY** [comment]
您好，邮件已收到

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.

**Pull request closed without merging**
