### PR TITLE
Add support for Swift Package Manager

### PR DESCRIPTION
**Pull request by wowpotato**
Xcode 11 introduce the support for Swift Package Manager (SwiftPM). 
it supports for not only Swift files, but also the C/C++ files.

So, SVProgressHUD should be supported. And I did this.
Add Package.swift and Add include folder for (Swift Package Manager with a Mixed Swift and Objective-C)

[Use Symlinks]
It requires that we provide symlinks to headers we want to make public.

### CODE REVIEW

**Comment by wowpotato** [comment]
> This looks good! Anything preventing it from being merged?

Nothing can stop us. 😁

**Review by mkonapelsky — APPROVED** [review]

**Comment by kirou** [comment]
I would like to use SPM, so I would like to request a merge.
Is there any reason why it can't be merged?

**Comment by daudelinAlarm** [comment]
Any idea when this could be merged??

**Review by arturo582 — APPROVED** [review]

**Comment by wowpotato** [comment]
All reviewers approved. 
When will it be merged?

**Review by arturo582 — APPROVED** [review]

**Review by arturo582 — APPROVED** [review]

**Review by arturo582 — APPROVED** [review]

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.

**Pull request closed without merging**
