### PR TITLE
Add option to customize only ring color, Add blur effect for custom design, rewrite indefinite animation view

### PR DESCRIPTION
**Pull request by Kaspik**
For our project we would like to have black text color but blue loading indicator ring color. Current implementation doesn't support this option so I wanted to support this library by adding this feature.

- Add option to set color only for image / loading indicator ring and keep text inside the progress hud black
- When this color is not set, we return `foregroundColor` itself - it's better than if user would need to set both to achieve change for both = by this way, there is 100% backwards compatibility just with added new feature
- Added option to have blur effect for custom style
- Changed the way how IndefiniteAnimatedView works - instead of image for mask use Gradient layer. this gives us option to specify custom lineJoin if necessary (can be added separately). The problem with mask image is described on gif here and shows problem when lineWidth is bigger than just few pixels

progress

Custom image color requested in https://github.com/SVProgressHUD/SVProgressHUD/issues/756.
Blur effect requested in https://github.com/SVProgressHUD/SVProgressHUD/issues/888.

- @honkmaster - I hope you find some time to take a look on this. :)

### CODE REVIEW

**Comment by honkmaster** [comment]
Looks good to me. Sorry, have very limited time. @juliensaad, your opinion?

**Comment by honkmaster** [comment]
Can you change the commit message of the squashed commit? I think the text does not reflect the changes very well.

**Comment by Kaspik** [comment]
@honkmaster Can we do squash merge so the text and commits is not shown and add proper text to the merge instead?

Btw., the code is already verified by few millions of users on production and everything looks okay!

**Comment by Kaspik** [comment]
@honkmaster Added changelog and bumped pod version so you can just release this without any effort. Also found issue where `SVProgressHUD-Framework` target had version of SDK 8.3 but project had 8.0 so made a change to make it consistent.

Ready for merge and release. :)

**Comment by honkmaster** [comment]
Thanks, this helps a lot as I don't have much spare time right now. Will merge this evening.

**Comment by Kaspik** [comment]
@honkmaster How you doing with the merge? :)

**Comment by Kaspik** [comment]
@honkmaster Please tell me you are able to merge this and release to cocoapods soon! :)

**Pull request merged**
