### PR TITLE
Solves bug where HUD doesn't disappear if show and dismiss are called one after the other

### PR DESCRIPTION
**Pull request by Vinzius**
Related to the issue:
SVProgressHUD/SVProgressHUD/issues/555

I think it should solve all the issues reported inside the ticket.

### CODE REVIEW

**Comment by honkmaster** [comment]
I already fixed that bug in a local branch. This is in my backup / time machine. As soon as my machine is back from repair I will compare the solutions and commit.

**Comment by berkkonak** [comment]
Hello, 

I am using below pod setting; 

`pod 'SVProgressHUD'`

For 'pod update', below printed;

`Using SVProgressHUD (2.0)`

and problem exists with this version.

Thanks for your help.

**Comment by honkmaster** [comment]
could you check the recent master

**Comment by berkkonak** [comment]
Hi, 

I checked below file;

`https://github.com/SVProgressHUD/SVProgressHUD/blob/master/SVProgressHUD/SVProgressHUD.m`

It looks different than the file loaded via cocoapods. In master, both show/dismiss methods (below methods) add operations with block. So it should be working with master version.
```
- (void)showProgress:(float)progress status:(NSString*)status
- (void)dismissWithDelay:(NSTimeInterval)delay 
```

Should I download this library manually and remove my pod definition, or is there any pod definition to pull master version?

Thanks for your help.

**Comment by honkmaster** [comment]
The version on the master has the fix. To use this version via cocoapods use `pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'` in your podsfile. However, if you wait a few hours I will push 2.0.1 to Cocoapods.

**Comment by berkkonak** [comment]
Thank you for your help and quick response.

**Pull request closed without merging**
