### PR TITLE
Created Package.swift

### PR DESCRIPTION
**Pull request by TheAbstractDev**
Created to use it with Swift Package Manager

### CODE REVIEW

**Comment by eytanschulman** [comment]
Any chance someone could approve this? 
@honkmaster 
@juliensaad

**Comment by dneykov** [comment]
Any update on this?

**Comment by igashev** [comment]
Would be great to have SPM support!

**Comment by anthonycastelli** [comment]
I would also love to see this merged in soon. I'm going through and replacing carthage with SPM and stripping out libraries I don't need anymore

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.

**Pull request closed without merging**
