### PR TITLE
iOS 13 support

### PR DESCRIPTION
**Pull request by Narendra-Pandey**

### CODE REVIEW

**Comment by jsaiti** [comment]
It crashes on iOS 12, because in this case: `UIScene *scene = [[[[UIApplication sharedApplication] connectedScenes] allObjects] firstObject];` need to check it for iOS version!

**Comment by Pearapps** [comment]
@honkmaster How does this look? Should there be a new release to support iOS 13?

**Comment by worldofnick** [comment]
@Pearapps we meet again...

yeah lets get an iOS 13 release...

**Comment by Kaspik** [comment]
@honkmaster @worldofnick Year and half later- any update on this? :)

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.

**Pull request closed without merging**
