### PR TITLE
To make Objective-C's enum easier to use even for swift

### PR DESCRIPTION
**Pull request by keisukeYamagishi**
I made enum written for Obejctive-C available with Swift style enum.

It became easier to use when using with swift.

### CODE REVIEW

**Comment by juliensaad** [comment]
This looks good, but will probably break compatibility with Swift users currently using it. I'd lean towards merging as the conventions are respected here. 

What are your thoughts @honkmaster ?

**Comment by keisukeYamagishi** [comment]
Does it affect swift users?
Rather, I could declare it explicitly, I felt good and created a PR.

If you are concerned, you may close it.

**Comment by honkmaster** [comment]
To be honest: I don't have a dedicated opinion on this because I don't use the component with Swift.

**Comment by juliensaad** [comment]
Same here ~ I would go ahead and merge since this is more standard.

**Pull request merged**
