### PR TITLE
Added support for Swift Package Manager | Fix Xcode 12.5 has invalid header layout

### PR DESCRIPTION
**Pull request by denandreychuk**

### CODE REVIEW

**Comment by harryblam** [comment]
Thanks for this PR, i've tested and is working well for me 👍

**Comment by MohammedBadr20s** [comment]
@harryblam How did imported it through this PR ?

**Comment by yarodevuci** [comment]
When it will be merged??

**Comment by harryblam** [comment]
> @harryblam How did imported it through this PR ?

@MohammedBadr20s  I referenced the branch repo in the package url in my package.json like this: `.package(name: "SVProgressHUD", url: "https://github.com/Pimine/SVProgressHUD.git", .branch("master")) `

**Review by nazgu1 — APPROVED** [review]

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.

**Pull request closed without merging**
