### PR TITLE
iOS7+ alert black dimming view has an alpha of 0.4, not 0.5

### PR DESCRIPTION
**Pull request by lmcd**

### CODE REVIEW

**Comment by honkmaster** [comment]
Why this change?

**Comment by lmcd** [comment]
Because this is the alpha Apple uses for `UIAlertController` in iOS. This makes the appearance of `SVProgressHUD` more closely align with native alerts, which is what `SVProgressHUDMaskTypeBlack` is attempting to mimic.

**Comment by honkmaster** [comment]
Hmm. I thought I checked this when setting this value back then. I currently have no Mac to evaluate, thus a visual comparison for this PR would be very helpful, such as the Hud and an alert side by side on a white background.

**Comment by honkmaster** [comment]
screen shot 2016-03-21 at 17 22 00

**Comment by honkmaster** [comment]
You are right. Thanks.

**Pull request merged**
