### PR TITLE
Fixed bundle problem

### PR DESCRIPTION
**Pull request by bimusiek**
This change allows other classes to extend SVProgressHUD.

### CODE REVIEW

**Comment by honkmaster** [comment]
Hi Michael, danke für den PR. Könntest du kurz erklären **warum** es das Bundle-Problem löst?

**Comment by bimusiek** [comment]
Hey. I am sorry but I do not speak German :( 
Problem is that when `SVProgressHUD` is bundled with CocoaPods it stays in Pods bundle. Then you get `NSBundle` from Pods. However, when you externalise it in your project then `NSBundle` returns you bundle of your app that does not have `SVProgressHUD.bundle` file.

**Comment by honkmaster** [comment]
Hi, i thought you might speak german because you are located in Berlin ;). Sorry for that. However, it seems you understood my question and yes very good explanation. Thanks for this good catch.

**Comment by bimusiek** [comment]
Google Translate :)

**Pull request closed without merging**
